import os

from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
SECURITY_PASSWORD_SALT = os.getenv("SECURITY_PASSWORD_SALT")
SECURITY_PASSWORD_HASH = os.getenv("SECURITY_PASSWORD_HASH")
TEST_USER_NAME = os.getenv("TEST_USER_NAME")
TEST_USER_EMAIL = os.getenv("TEST_USER_EMAIL")
TEST_USER_PASSWORD = os.getenv("TEST_USER_PASSWORD")
TEST_ADMIN_EMAIL = os.getenv("TEST_ADMIN_EMAIL")
TEST_PASSWORD = os.getenv("TEST_PASSWORD")